version: '1'
services:
  hotel_reservas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@hkh8nor6id4iu8l4_tp?TNS_ADMIN=/app/oracle_wallet
      - spring.datasource.username=HOTEL
      - spring.datasource.password=Duoc$2024.#0211
    restart: always